[app]
useragent = 'Stupid weather app'
useremail = 'email@lol.email'

[text.h1]
source_file = 'Anton-Regular.ttf'
web_source = 'https://github.com/google/fonts/blob/main/ofl/anton/Anton-Regular.ttf?raw=true'
size = 90

[text.sub]
source_file = 'Anton-Regular.ttf'
web_source = 'https://github.com/google/fonts/blob/main/ofl/anton/Anton-Regular.ttf?raw=true'
size = 45

[text.h2]
source_file = 'Grotesk.ttf'
web_source = 'https://github.com/google/fonts/blob/main/ofl/schibstedgrotesk/SchibstedGrotesk%5Bwght%5D.ttf?raw=true'
size = 30

[text.h3]
source_file = 'Grotesk.ttf'
web_source = 'https://github.com/google/fonts/blob/main/ofl/schibstedgrotesk/SchibstedGrotesk%5Bwght%5D.ttf?raw=true'
size = 18

[text.h4]
source_file = 'Grotesk.ttf'
web_source = 'https://github.com/google/fonts/blob/main/ofl/schibstedgrotesk/SchibstedGrotesk%5Bwght%5D.ttf?raw=true'
size = 14

[text.h4_symbols]
source_file = 'NotoSymbols2.ttf'
web_source = 'https://github.com/notofonts/noto-fonts/blob/main/unhinted/ttf/NotoSansSymbols2/NotoSansSymbols2-Regular.ttf?raw=true'
size = 14

[graphics.rain]
source_file = 'rain.png'
web_source = 'https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/72/emoji_u1f327.png'

[graphics.wind]
source_file = 'wind.png'
web_source = 'https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/72/emoji_u1f38f.png'

[color]
bg = 255
h1 = 128
h2 = 0

[feed]
items = 6

[api.openmeteo.grid]
lat = 40.7325
long = -73.9560

[api.nws]
station = "ILN"

[api.nws.grid]
x = 35
y = 36

[display]
rotate = false
